# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - GCSE-APP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:  # Define environment variables for Azure authentication and deployment
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_72740D4EAEAA4146A9C1D3D1A190F99D}}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP}}
      WEBAPP_NAME: ${{ secrets.WEBAPP_NAME}}

    steps:
      - name: Download Azure CLI
        uses: actions/download-artifact@v4  # Use the Azure CLI action
      - name: Login to Azure
        run: |
          az login --service-principal -u "$AZURE_SPN_CLIENT_ID" -p "$AZURE_SPN_CLIENT_SECRET" -t "$AZURE_TENANT_ID"
        env:  # Use secrets for security
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_86656780EFC64741AC48FB3ECBA3A241}}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B75F33ED9ABE4DB18455CB21F83554AE}}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_72740D4EAEAA4146A9C1D3D1A190F99D}}

      - name: 'Deploy to Azure Web App'
        run: | 
          