name: Deploy Docker Image to Azure Web App - GCSE-APP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_72740D4EAEAA4146A9C1D3D1A190F99D}}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP}}
      WEBAPP_NAME: ${{ secrets.WEBAPP_NAME}}
      AZURE_SPN_CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_86656780EFC64741AC48FB3ECBA3A241}}
      AZURE_SPN_CLIENT_SECRET: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET_FF452D9373A04A0FA807D5204C4A84F2}}
      AZURE_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_B75F33ED9ABE4DB18455CB21F83554AE}}

    steps:
      - name: Login to Azure
        run: |
          az login --service-principal -u "$AZURE_SPN_CLIENT_ID" -p "$AZURE_SPN_CLIENT_SECRET" -t "$AZURE_TENANT_ID"

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull lazherhassine/pfe-app:latest

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name $WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP \
          --docker-custom-image-name lazherhassine/pfe-app:latest \
          --subscription $AZURE_SUBSCRIPTION_ID
